In [1]:
!pip install opendatasets


  DEPRECATION: kaggle is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip



  Using cached opendatasets-0.1.22-py3-none-any.whl (15 kB)
     ---------------------------------------- 78.3/78.3 kB 1.4 MB/s eta 0:00:00
     -------------------------------------- 84.6/84.6 kB 476.5 kB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached click-8.1.7-py3-none-any.whl (97 kB)
     ------------------------------------ 162.8/162.8 kB 375.6 kB/s eta 0:00:00
     ---------------------------------------- 78.2/78.2 kB 1.1 MB/s eta 0:00:00
  Running setup.py install for kaggle: started
  Running setup.py install for kaggle: finished with status 'done'


In [2]:
import numpy as np
import pandas as pd
import opendatasets as od

In [4]:
od.download("https://www.kaggle.com/datasets/rahulvyasm/medical-insurance-cost-prediction?resource=download")

Skipping, found downloaded files in ".\medical-insurance-cost-prediction" (use force=True to force download)


In [47]:
df=pd.read_csv("medical-insurance-cost-prediction\medical_insurance.csv")

In [48]:
target=df['charges']

In [49]:
df.drop(['charges'],inplace=True,axis=1)

In [9]:
!pip install scikit-learn


[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [50]:
from sklearn.preprocessing import LabelEncoder,MinMaxScaler

In [51]:
sEncoder=LabelEncoder()
SmEncoder=LabelEncoder()
REncoder=LabelEncoder()

In [52]:
df['sex']=sEncoder.fit_transform(df['sex'])
df['smoker']=SmEncoder.fit_transform(df['smoker'])
df['region']=REncoder.fit_transform(df['region'])

In [53]:
df

age  sex     bmi  children  smoker  region
0      19    0  27.900         0       1       3
1      18    1  33.770         1       0       2
2      28    1  33.000         3       0       2
3      33    1  22.705         0       0       1
4      32    1  28.880         0       0       1
...   ...  ...     ...       ...     ...     ...
2767   47    0  45.320         1       0       2
2768   21    0  34.600         0       0       3
2769   19    1  26.030         1       1       1
2770   23    1  18.715         0       0       1
2771   54    1  31.600         0       0       3

[2772 rows x 6 columns]

In [54]:
scaler=MinMaxScaler()

In [55]:
df=scaler.fit_transform(df)

In [18]:
df

array([[0.02173913, 0.        , 0.3212268 , 0.        , 1.        ,
        1.        ],
       [0.        , 1.        , 0.47914985, 0.2       , 0.        ,
        0.66666667],
       [0.2173913 , 1.        , 0.45843422, 0.6       , 0.        ,
        0.66666667],
       ...,
       [0.02173913, 1.        , 0.27091741, 0.2       , 1.        ,
        0.33333333],
       [0.10869565, 1.        , 0.07411891, 0.        , 0.        ,
        0.33333333],
       [0.7826087 , 1.        , 0.42076944, 0.        , 0.        ,
        1.        ]])

In [56]:
from sklearn.model_selection import train_test_split

In [57]:
X_train,X_test,Y_train,Y_test=train_test_split(df,target,test_size=0.3,random_state=6)

In [58]:
print(X_train)

[[0.86956522 1.         0.49582997 0.         0.         0.33333333]
 [0.86956522 0.         0.55205811 0.         0.         0.33333333]
 [0.17391304 1.         0.45574388 0.4        1.         1.        ]
 ...
 [0.02173913 0.         0.4613936  0.         1.         0.66666667]
 [0.86956522 0.         0.69814366 0.         0.         0.66666667]
 [0.7826087  0.         0.53416734 0.6        0.         0.33333333]]


In [59]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error,r2_score


In [60]:
rf_regressor = RandomForestRegressor(n_estimators=100, random_state=6)

In [61]:
rf_regressor.fit(X_train,Y_train)

RandomForestRegressor(random_state=6)

In [62]:
Y_test

1429     6313.75900
917     35069.37452
836      4402.23300
193     12044.34200
617     23306.54700
           ...     
272      7265.70250
2013    11326.71487
2675     7147.47280
2409     1711.02680
1992     3558.62025
Name: charges, Length: 832, dtype: float64

In [63]:
ans=rf_regressor.predict(X_test)

In [64]:
r2_score(ans,Y_test)

0.9502194177395481

In [65]:
ans

array([ 6658.3095346 , 29359.5975097 ,  4455.5967665 , 15780.1771334 ,
       23560.6311295 , 39780.2317839 , 14321.595169  ,  9106.3732251 ,
       34750.24829   ,  6913.1404935 , 14026.860805  ,  6065.6026931 ,
       19013.709825  ,  8129.5245804 , 12894.1853652 ,  3475.927344  ,
       19077.53394   ,  2226.6465595 , 22892.7476618 ,  2472.463092  ,
        5402.8501209 ,  7212.103302  , 20001.8478349 ,  3753.8020409 ,
       13391.0074525 , 25799.102105  ,  2993.5463586 ,  4639.2047568 ,
        5819.1846083 ,  2550.1076839 , 10558.3825364 ,  4670.494459  ,
        3024.1916059 ,  5206.388194  , 19324.5370183 ,  7034.238707  ,
        3938.0915479 ,  4883.932777  , 45307.9293852 , 12726.8799838 ,
       48252.3291816 ,  5819.1846083 ,  4519.176906  ,  7527.7026473 ,
       10336.5598155 , 16551.3973231 ,  2680.786106  ,  7807.2417338 ,
        4046.63287351, 33567.7603195 , 14103.0151734 ,  6175.3836185 ,
        5258.6574462 ,  3325.49558783, 48051.1134731 ,  2141.241124  ,
      

In [66]:
import pickle

# Serialize objects
serialized_objects = {
    'model': rf_regressor,
    'scaler': scaler,
    'sEncoder':sEncoder,
'SmEncoder':SmEncoder,
'REncoder':REncoder
}

# Save serialized objects to file
with open('package.pkl', 'wb') as f:
    pickle.dump(serialized_objects, f)

print("Package created successfully!")

Package created successfully!


In [67]:
arr=X_train[0].reshape(-1,1)

In [68]:
arr.shape

(6, 1)

In [69]:
import os
print(os.getcwd())

c:\Users\SUMIT\Desktop\project\app


In [77]:
import pickle

# Load serialized objects from file
with open('package.pkl', 'rb') as f:
    serialized_objects = pickle.load(f)

# Access the objects
model = serialized_objects['model']
scaler = serialized_objects['scaler']
sEncoder=serialized_objects['sEncoder']
SmEncoder=serialized_objects['SmEncoder']
REncoder=serialized_objects['REncoder']



In [78]:
arr=np.array([0.86956522 ,1 ,0.49582997,0, 0,0.33333333]).reshape(1,-1)

In [79]:
model.predict(arr)


array([11723.463237])

In [85]:

sEncoder.transform(['female'])[0]

0

In [82]:
SmEncoder.transform(['no'])

array([0])

In [83]:
REncoder.transform(['southeast'])

array([2])